sudo: false
language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env: WITH_COVERAGE=true
    - php: 7
    - php: hhvm

before_install:
  - if [[ "$WITH_COVERAGE" != "true" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer selfupdate

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-text; else vendor/bin/phpunit; fi
